name: PKUAutoSubmit

on:
  schedule:
    - cron: '20 0,4,8 * * 1,2,3,4,5,6,0'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
          python main.py --USERNAME ${{secrets.USERNAME}} --PASSWORD ${{secrets.PASSWORD}} 
          

